# Docs: https://github.com/Azure/webapps-deploy
name: 'Build and deploy JAR app to Azure Web App: app-pg-rm556219'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build com as credenciais do banco vindas dos Secrets (como você pediu)
      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-pg-rm556219'             # seu Web App
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # se seu secret tem OUTRO nome (ex.: AzureAppService_PublishProfile_XXXX), troque a linha acima
          package: 'build/libs/*.jar'
